#!/bin/bash



myFile=mem_`date +%F_%T`.txt

touch "$myFile"

cpu="cpu_ld"

echo -n "date" >> "$myFile"
echo -n "          " >> "$myFile"
echo -n "time" >> "$myFile"
echo -n "         " >> "$myFile"

echo -n "$cpu" >> "$myFile" 
echo -n "   " >> "$myFile"

############
#User Input#
############################################
#for var in $@
#do
#        echo -n "$var" >> "$myFile"
#        echo -n "   " >> "$myFile"
#
#done
###########################################



while read line
do
	 echo -n "$line" >> "$myFile"
         echo -n "   " >> "$myFile"
done < "conf"
		




echo >> "$myFile"

while true
do

	echo -n `date +%F` >> "$myFile"
	echo -n "    " >> "$myFile"
        echo -n `date +%T` >> "$myFile"
	echo -n "     " >> "$myFile"

        echo -n `cat /proc/loadavg | cut -c 1-4` >> "$myFile"

        y=${#cpu}

        while [ $y -gt 1 ]

        do
             echo -n " " >> "$myFile"
             y=$(( $y - 1 )) 

        done


        while read var

        do

            #echo -n `ps -eo pmem,args | grep "$var" | grep -v grep | cut -c 2-4`
            #echo "     "
            cmd=`ps -eo pmem,args | grep "$var" | grep -v grep | grep -v bash | cut -c 2-4`
            echo -n "$cmd" >> "$myFile"

            x=${#var}

            while [ $x -gt 0 ]
            do
                  echo -n " " >> "$myFile"
                  x=$(( $x - 1 ))
            done



        done < "conf"

        echo >> "$myFile"

        sleep 10

done

